services:
  php:
    image: tugboatqa/php:7.3-apache
    default: true
    depends: mysql
    commands:
      init:
        - docker-php-ext-install opcache
        - a2enmod headers rewrite
        - wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar
        - chmod +x /usr/local/bin/drush
        - echo "memory_limit = 2G" >> /usr/local/etc/php/conf.d/my-php.ini
        - composer self-update --1
      update:
        - cd /var/www/
        - composer create-project drupal/recommended-project drupal
        - ln -snf /var/www/drupal $DOCROOT
        - cd /var/www/drupal
        - sed -i "s/self\.version/${TUGBOAT_GITLAB_TARGET:-$TUGBOAT_PREVIEW}/g" composer.json
        - composer install --optimize-autoloader
        - composer require drush/drush
        - drush --yes --db-url=mysql://tugboat:tugboat@mysql:3306/tugboat --account-name=admin --account-pass=admin site:install standard
      build:
        - composer install --optimize-autoloader
        - drush updatedb -y
        - drush cache:rebuild
  mysql:
    image: tugboatqa/mariadb:10
