services:
  php:
    image: tugboatqa/php:7.3-apache
    default: true
    depends: mysql
    commands:
      init:
        - docker-php-ext-install opcache
        - a2enmod headers rewrite
        - ln -snf $TUGBOAT_ROOT $DOCROOT
        - composer global require drush/drush:8.*
        - ln -s ~/.composer/vendor/bin/drush /usr/local/bin/drush
      update:
        - mkdir -p "${DOCROOT}/sites/default/files"
        - chgrp -R www-data "${DOCROOT}/sites/default/files"
        - find "${DOCROOT}/sites/default/files" -type d -exec chmod 2775 {} \;
        - find "${DOCROOT}/sites/default/files" -type f -exec chmod 0664 {} \;
        - drush --yes --db-url=mysql://tugboat:tugboat@mysql:3306/tugboat --account-name=admin --account-pass=tugboat site:install standard
      build:
        - drush updatedb -y
        - drush cc all
  mysql:
    image: tugboatqa/mariadb:10
